### PR TITLE
update doc and help page

### PR DESCRIPTION
**Pull request by yaohuan771634**

### CODE REVIEW

**Comment by PHILO-HE** [comment]
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by PHILO-HE** [comment]
accessCount(interval) | ac | Access counts during the last time interval
accessCountTop(interval) | acTop | The topmost number for access counts during the last time interval
accessCountBottom(interval) | acBot | The bottommost number for access counts during the last time interval
accessCountTopOnStoragePolicy(interval, "$StoragePolicy") | acTopSp | The topmost number for access counts with regard to a storage  policy during the last time interval. The supported HDFS storage policies are COLD, WARM, HOT,  ONE_SSD, ALL_SSD, LAZY_PERSIST
accessCountBottomOnStoragePolicy(interval, "$StoragePolicy") | acBotSp | The bottommost number for access counts with regard to a storage policy during the last time interval
age | - | The time span from last modification moment to now
atime | - | The last access time
blocksize | - | The block size of file
inCache | - |  The file is in cache storage
isDir | - |  The file is a directory
length | - | The length of file
mtime | - | The last modification time of file
path | - | The file path in HDFS
storagePolicy | - | The storage policy of file
unsynced | - |  The file is not synced

**Comment by PHILO-HE** [comment]
#1782

**Comment by littlezhou** [comment]
@PHILO-HE Please also include the change made in #1770, thanks!

**Comment by PHILO-HE** [comment]
accessCount(interval) | ac | The access counts during the last time interval
accessCountTop(interval, N) | acTop | The topmost N access counts during the last time interval
accessCountBottom(interval, N) | acBot | The bottommost N access counts during the last time interval
accessCountTopOnStoragePolicy(interval, N, "$StoragePolicy") | acTopSp | The topmost N access counts with regard to a storage policy during the last time interval. The supported HDFS storage policies are COLD, WARM, HOT, ONE_SSD, ALL_SSD, LAZY_PERSIST
accessCountBottomOnStoragePolicy(interval, N, "$StoragePolicy") | acBotSp | The bottommost N access counts with regard to a storage policy during the last time interval

**Comment by PHILO-HE** [comment]
sleep | -m $millisecond   | Sleep $millisecond
sync  | -dest $dest | Sync file to $dest

**Comment by PHILO-HE** [comment]
echo -msg $message

**Pull request merged**
