### PR TITLE
Mysql5.6 compatibility of utf-8.

### PR DESCRIPTION
**Pull request by hddong**
Index can not longer than 767 bytes when use mysql5.6, but one characters takes up three bytes with UTF-8 of Chinese. In that case, index must not longer than 255.

### CODE REVIEW

**Comment by philo-he** [comment]
Thanks @hddong for your patch. It looks that this patch can help solve incompatibility issue when UTF-8 Chinese character is used in Mysql 5.6. But the provided property name 'utf8.enable' is too general. And I am thinking for Chinese character, different encoding requires different bytes, it looks hard to solve all such incompatibility issues. Any thought? Hope I am not missing something.

**Comment by hddong** [comment]
@PHILO-HE yep, `different encoding requires different bytes` I thought it too and I think we can config it as `SMART_METASTORE_CHARACTER_TAKEUP_BYTES`, then calculate max long of mysql5.6 in `sqlCompatibility`.

**Comment by philo-he** [comment]
The new patch is more general to solve this issue. Some minor suggestions:

1) Change SMART_METASTORE_CHARACTER_TAKEUP_BYTES to SMART_METASTORE_CHARACTER_TAKEUP_BYTES_KEY. And add a default value by defining
SMART_METASTORE_CHARACTER_TAKEUP_BYTES_DEFAULT = 1.
2) Add the new property to a config template: conf/smart-default.xml, and include a description for it.
3) In trouble shooting section of ssm-deployment-guide.md, we once mentioned this issue, you can document your helpful information here.
4) I guess you have validated the patch on mysql 5.6. If not, please kindly do it.

**Comment by hddong** [comment]
@PHILO-HE thanks, I have checked it on mysql 5.6. And added description in trouble shooting section, please have a review.

**Comment by philo-he** [comment]
Thanks @hddong so much for your new update on the patch. I will have a final test and if no issue is found, I will merge the patch today.

**Comment by philo-he** [comment]
Thanks @hddong again for you contribution, the patch looks good and has been merged.

**Pull request merged**
