### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by huafengw** [comment]
Potential ConcurrentModificationException
```
Exception in thread "org.smartdata.server.command.CommandExecutor" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
	at org.smartdata.server.command.CommandExecutor.batchCommandStatusUpdate(CommandExecutor.java:434)
	at org.smartdata.server.command.CommandExecutor.schedule(CommandExecutor.java:345)
	at org.smartdata.server.command.CommandExecutor.run(CommandExecutor.java:130)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by huafengw** [comment]
Build finally succeed again! @littlezhou

**Comment by littlezhou** [comment]
@huafengw Holy NICE!

**Comment by huafengw** [comment]
Should I merge?

**Pull request merged**
